# render.yaml
services:
  - type: web
    name: chat-room
    env: node
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18
    plan: free